---
# eid, fp参数必须填写
# 随意填写可能导致订单无法提交等问题
eid: abc
fp: def
sku_id: 100012043978
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36